"""
Copyright 2026 Veil Development Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import http
import json
import quart
from weaver_framework.microservice.api_response import ApiResponse
from weaver_framework.microservice.base_api_route import BaseApiRoute, validate_json
from weaver_framework.microservice.http_content_type import HttpContentType
from veil.identity_service.routes.route_injections import RouteInjections
from veil.identity_service.database.database_manager import DatabaseManager


SCHEMA_REGISTER_ACCOUNT_REQUEST: dict = {
    "$schema": "http://json-schema.org/draft-07/schema#",

    "type": "object",
    "additionalProperties": False,

    "properties":
    {
        "display_name":
            {
                "type": "string",
                "minLength": 4,
                "maxLength": 64
            },
        "email_address":
            {
                "type": "string",
                "format": "email",
                "minLength": 3,
                "maxLength": 320
            },
        "password":
            {
                "type": "string",
                "minLength": 8,
                "maxLength": 128
            },
    },
    "required": ["email_address", "password"]
}


def create_blueprint(injections: RouteInjections) -> quart.Blueprint:
    new_route = RegisterAccountRoute(injections)

    blueprint = quart.Blueprint('register_account', __name__)

    injections.logger.debug("=> %s POST /accounts/register",
                            'Register new account'.ljust(40))

    @blueprint.route('/accounts/register', methods=['POST'])
    async def register_account_request() -> quart.Response:
        """Handle incoming account registration requests.

        Returns:
            The HTTP response generated by the register account route.
        """
        return await new_route.register_account()

    return blueprint


class RegisterAccountRoute(BaseApiRoute):
    """Route handler for account registration endpoints."""

    def __init__(self, injections: RouteInjections) -> None:
        self._logger = injections.logger.getChild(__name__)
        self._injections: RouteInjections

    @validate_json(SCHEMA_REGISTER_ACCOUNT_REQUEST)
    async def register_account(self, request_msg: ApiResponse) -> quart.Response:
        """Handle an account registration request.

        Returns:
            A JSON HTTP response indicating the result of the
            registration request.
        """
        return quart.Response(json.dumps({}),
                              status=http.HTTPStatus.OK,
                              content_type=HttpContentType.JSON)
