"""
Copyright 2026 Veil Development Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import hashlib
import http
import json
import quart
from weaver_framework.microservice.api_response import ApiResponse
from weaver_framework.microservice.base_api_route import BaseApiRoute, validate_json
from weaver_framework.microservice.http_content_type import HttpContentType
from veil.identity_service.database.account_repository import AccountRepository
from veil.identity_service.routes.route_injections import RouteInjections


SCHEMA_REGISTER_ACCOUNT_REQUEST: dict = {
    "$schema": "http://json-schema.org/draft-07/schema#",

    "type": "object",
    "additionalProperties": False,

    "properties":
    {
        "display_name":
            {
                "type": "string",
                "minLength": 4,
                "maxLength": 64
            },
        "email_address":
            {
                "type": "string",
                "format": "email",
                "minLength": 3,
                "maxLength": 320
            },
        "password":
            {
                "type": "string",
                "minLength": 8,
                "maxLength": 128
            },
    },
    "required": ["display_name", "email_address", "password"]
}
"""JSON schema for account registration requests.

The request body must contain a display name, email address, and
password used to create a new account.

Schema Rules:
    * ``display_name`` must be between 4 and 64 characters.
    * ``email_address`` must be a valid email address and between
      3 and 320 characters.
    * ``password`` must be between 8 and 128 characters.
    * Additional unknown properties are rejected.
"""


def create_blueprint(injections: RouteInjections) -> quart.Blueprint:
    """Create the account registration API blueprint.

    Registers the ``POST /accounts/register`` endpoint and binds it
    to :class:`RegisterAccountRoute`.

    Args:
        injections: Shared route dependencies and service injections.

    Returns:
        The configured Quart blueprint containing the account
        registration endpoint.
    """
    new_route = RegisterAccountRoute(injections)

    blueprint = quart.Blueprint('register_account', __name__)

    injections.logger.debug("=> %s POST /accounts/register",
                            'Register new account'.ljust(40))

    @blueprint.route('/accounts/register', methods=['POST'])
    async def register_account_request() -> quart.Response:
        """Handle incoming account registration requests.

        Returns:
            The HTTP response generated by the register account route.
        """
        # pylint: disable=no-value-for-parameter
        return await new_route.register_account()

    return blueprint


class RegisterAccountRoute(BaseApiRoute):
    """Route handler for account registration operations."""

    def __init__(self, injections: RouteInjections) -> None:
        """Initialize the register account route handler.

        Args:
            injections: Shared route dependencies and injected services.
        """
        self._logger = injections.logger.getChild(__name__)
        self._injections: RouteInjections = injections

    @validate_json(SCHEMA_REGISTER_ACCOUNT_REQUEST)
    async def register_account(self,
                               request_msg: ApiResponse) -> quart.Response:
        """Register a new user account.

        Validates the incoming registration request, checks for
        duplicate email addresses and display names, hashes the
        supplied password, and creates a new account record.

        Args:
            request_msg: Parsed API request containing the validated
                registration payload.

        Returns:
            A Quart HTTP response containing either the newly created
            user ID or an error response describing the failure.
        """

        email_address: str = request_msg.body["email_address"].strip().lower()
        display_name: str = request_msg.body["display_name"].strip()
        raw_password: str = request_msg.body["password"]
        password_hash: str = hashlib.sha256(
            raw_password.encode("utf-8")).hexdigest()

        account_repo: AccountRepository = self._injections.account_repository

        if account_repo.email_address_exists(email_address):
            return quart.Response(
                json.dumps({"error": "email address already exists"}),
                status=http.HTTPStatus.CONFLICT,
                content_type=HttpContentType.JSON)

        if account_repo.display_name_exists(display_name):
            return quart.Response(
                json.dumps({"error": "display name already exists"}),
                status=http.HTTPStatus.CONFLICT,
                content_type=HttpContentType.JSON)

        user_id: str | None = account_repo.create_account(email_address,
                                                          display_name,
                                                          password_hash)

        if user_id is None:
            self._logger.error(
                "Failed to create account for email address '%s'",
                email_address)
            return quart.Response(
                json.dumps({"error": "failed_to_create_account"}),
                status=http.HTTPStatus.INTERNAL_SERVER_ERROR,
                content_type=HttpContentType.JSON)

        response_body: dict = {
            "user_id": user_id
        }
        return quart.Response(json.dumps(response_body),
                              status=http.HTTPStatus.CREATED,
                              content_type=HttpContentType.JSON)
